# docker compose up -d
# http://localhost:8888/
# Login: Password1 (Is enable login)

services:
  jupyterlab:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jupyterlab-tools
    ports:
      - "8888:8888"
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:8888/api/kernels | grep -q 'kernel_id' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 15s
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      OPENAI_API_KEY: "<YOUR_KEY>"
      JUPYTERLAB_MEM_LIMIT: "2G"
    volumes:
      - ./workspace:/home/jupyter/works
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 60s
      resources:
        limits:
          memory: 4G
          cpus: "2.0"
        reservations:
          memory: 2G
          cpus: "1.0"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
